// Generated by CoffeeScript 1.8.0
(function() {
  var $janishPlus, DRAGGING_ILLUSION_FROM_LIST, DRAGGING_ILLUSION_FROM_PANEL, DRAGGING_OUTPUT_FROM_PANEL, colHeight, currentDraggingData, currentDraggingType, currentIllusionList, documentReady, drawJanish, drawPadding, illusionDict, illusions, loadIllusions, loadJanish, logLocation, panel_janish, setupDropEvent, templateJanishItem, templateJanishSub;

  illusions = null;

  illusionDict = {};

  currentIllusionList = 0;

  currentDraggingType = 0;

  currentDraggingData = null;

  DRAGGING_ILLUSION_FROM_LIST = 1;

  DRAGGING_ILLUSION_FROM_PANEL = 2;

  DRAGGING_OUTPUT_FROM_PANEL = 3;

  panel_janish = [
    {
      "id": "list_file_1",
      "illusion": "LS",
      "input": {
        "path": "."
      }
    }, {
      "id": "for_each_1",
      "illusion": "FOR",
      "input": {
        "list": "#list_file_1.file_list"
      },
      "sub": {
        "body": [
          {
            "id": "print_2",
            "illusion": "PRINT",
            "input": {
              "content": "#for_each_1.iterator"
            }
          }, {
            "id": "for_each_1",
            "illusion": "FOR",
            "input": {
              "list": "#list_file_1.file_list"
            }
          }
        ]
      }
    }, {
      "id": "print_3",
      "illusion": "PRINT",
      "input": {
        "content": "meh"
      }
    }
  ];

  logLocation = function() {
    var $illusion1;
    $illusion1 = $("#illusion-2");
    console.log($("#illusion-1").position());
    console.log($("#illusion-2").position());
    return console.log($("#illusion-3").position());
  };

  loadIllusions = function() {
    var $illusionList, $illusionType, $item, createDragStart, i, ill, illusion, illusionType, setChangeCurrentIllusionList, str_i, templateIllusionItem, templateIllusionTypeItem, _i, _j, _len, _len1, _ref, _ref1, _results;
    for (_i = 0, _len = illusions.length; _i < _len; _i++) {
      illusionType = illusions[_i];
      _ref = illusionType["list"];
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        illusion = _ref[_j];
        illusionDict[illusion["illusion"]] = illusion;
      }
    }
    templateIllusionTypeItem = _template($("#template-illusion-type-item").html());
    $illusionType = $("#illusion-type");
    $illusionType.html("");
    for (str_i in illusions) {
      ill = illusions[str_i];
      i = parseInt(str_i);
      if (currentIllusionList === i) {
        ill["current"] = true;
      } else {
        ill["current"] = false;
      }
      $item = $(templateIllusionTypeItem(ill));
      setChangeCurrentIllusionList = function() {
        var newListId, onClick;
        newListId = i;
        onClick = function() {
          currentIllusionList = newListId;
          return loadIllusions();
        };
        return onClick;
      };
      $item.click(setChangeCurrentIllusionList());
      $illusionType.append($item);
    }
    templateIllusionItem = _template($("#template-illusion-item").html());
    $illusionList = $("#illusion-list");
    $illusionList.html("");
    _ref1 = illusions[currentIllusionList]["list"];
    _results = [];
    for (str_i in _ref1) {
      ill = _ref1[str_i];
      $item = $(templateIllusionItem(ill));
      createDragStart = function() {
        var currentIll, dragStart;
        currentIll = ill;
        dragStart = function() {
          currentDraggingType = DRAGGING_ILLUSION_FROM_LIST;
          return currentDraggingData = currentIll;
        };
        return dragStart;
      };
      $item.on("dragstart", createDragStart());
      _results.push($illusionList.append($item));
    }
    return _results;
  };

  setupDropEvent = function() {
    $(".illusion-plus").on("dragover", function(e) {
      e.preventDefault();
      return $(this).addClass("drag-over");
    });
    $(".illusion-plus").on("dragleave", function(e) {
      e.preventDefault();
      return $(this).removeClass("drag-over");
    });
    return $(".illusion-plus").on("drop", function(e) {
      console.log(currentDraggingType);
      return console.log(currentDraggingData);
    });
  };

  colHeight = function(col) {
    var $col, $last;
    $col = $("#janish-col-" + col);
    $last = $col.children().last();
    if ($last.length) {
      return $last.position().top + $last.height() + 45;
    } else {
      return 0;
    }
  };

  drawPadding = function(col, height) {
    var $padding;
    if (height - 7 - colHeight(col) > 0) {
      $padding = $("<div></div>");
      $padding.css("height", height - colHeight(col));
      return $("#janish-col-" + col).append($padding);
    }
  };

  templateJanishItem = _template($("#template-janish-item").html());

  templateJanishSub = _template($("#template-janish-sub").html());

  $janishPlus = $("#template-janish-plus").html();

  drawJanish = function(janish, col) {
    var $janish, base_height, c, count, h, i, illusion, item, j, key, min, name, output, sub_janish, sub_list, _i, _j, _k, _len, _len1, _ref, _ref1, _results, _results1;
    if (Array.isArray(janish)) {
      _results = [];
      for (_i = 0, _len = janish.length; _i < _len; _i++) {
        j = janish[_i];
        _results.push(drawJanish(j, col));
      }
      return _results;
    } else {
      illusion = illusionDict[janish["illusion"]];
      min = 0;
      for (i = _j = _ref = col + 1; _ref <= 20 ? _j < 20 : _j > 20; i = _ref <= 20 ? ++_j : --_j) {
        h = colHeight(i);
        if (h > min) {
          min = h;
        }
      }
      drawPadding(col, min);
      $janish = $(templateJanishItem(illusion));
      $("#janish-col-" + col).append($janish);
      if (illusion.sub) {
        count = 0;
        sub_list = [];
        _ref1 = illusion.sub;
        for (key in _ref1) {
          output = _ref1[key];
          sub_list.push({
            "name": key,
            "output": output
          });
        }
        sub_list.reverse();
        base_height = $janish.position().top;
        _results1 = [];
        for (_k = 0, _len1 = sub_list.length; _k < _len1; _k++) {
          item = sub_list[_k];
          name = item["name"];
          output = item["output"];
          c = col + Object.keys(illusion.sub).length - count;
          count++;
          drawPadding(c, base_height);
          $("#janish-col-" + c).append(templateJanishSub(item));
          if (janish["sub"] && janish["sub"][name]) {
            sub_janish = janish["sub"][name];
            drawJanish(sub_janish, c);
          }
          _results1.push($("#janish-col-" + c).append($janishPlus));
        }
        return _results1;
      }
    }
  };

  loadJanish = function() {
    var $item, $janishPanel, i, _i;
    console.log(panel_janish);
    $janishPanel = $("#janish-panel");
    $janishPanel.html("");
    for (i = _i = 0; _i < 20; i = ++_i) {
      $item = $('<div class="janish-col"></div>');
      $item.attr("id", "janish-col-" + i);
      $janishPanel.append($item);
    }
    drawJanish(panel_janish, 0);
    return $("#janish-col-0").append($janishPlus);
  };

  documentReady = function() {
    $.ajax({
      "url": "illusions.json",
      "dataType": "json",
      "success": function(data) {
        illusions = data;
        loadIllusions();
        return loadJanish();
      }
    });
    return setupDropEvent();
  };

  $(document).ready(documentReady);

}).call(this);

//# sourceMappingURL=editor.js.map
