// Generated by CoffeeScript 1.8.0
(function() {
  var documentReady;

  documentReady = function() {
    return console.log("document ready");
  };

  $(document).ready(documentReady);

}).call(this);

//# sourceMappingURL=editor.js.map
